@startuml

actor Administrador

Administrador --> (Registrar Producto)
Administrador --> (Consultar Productos)
Administrador --> (Actualizar Producto)
Administrador --> (Eliminar Producto)
Administrador --> (Registrar Venta)

@enduml
